[project]
name = "workflow-rag-agent"
version = "0.1.0"
description = "Agentic workflows using LangChain"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "datasets>=4.4.1",
    "dotenv>=0.9.9",
    "evalplus>=0.3.1",
    "langchain-anthropic>=1.2.0",
    "langchain-ollama>=1.1.0",
    "langchain[openai]>=1.2.15",
    "langgraph>=1.1.10",
    "matplotlib>=3.10.0",
    "pandas>=2.2.0",
]
